"""empty message

Revision ID: 08c368d82e5a
Revises: 8c98001248df
Create Date: 2018-12-28 06:10:17.351155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08c368d82e5a'
down_revision = '8c98001248df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('avatarUrl', sa.String(length=255), nullable=True))
    op.drop_column('member', 'avatarUr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('avatarUr', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('member', 'avatarUrl')
    # ### end Alembic commands ###
