"""empty message

Revision ID: 0dabfeb70247
Revises: 8e57c8ddd6d7
Create Date: 2018-12-28 06:02:38.468992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dabfeb70247'
down_revision = '8e57c8ddd6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_member_bind',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('client_type', sa.String(length=20), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('openid', sa.String(length=80), nullable=False),
    sa.Column('unionid', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('auth_member_bind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_member_bind',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('client_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('openid', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('unionid', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('oauth_member_bind')
    # ### end Alembic commands ###
