"""empty message

Revision ID: 258358ad087e
Revises: 66d9bd9e74eb
Create Date: 2018-12-28 04:03:19.727601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '258358ad087e'
down_revision = '66d9bd9e74eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('mobile', table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mobile', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('nickName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('gender', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('salt', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('reg_id', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('mobile', 'member', ['mobile'], unique=True)
    # ### end Alembic commands ###
