"""empty message

Revision ID: 66d9bd9e74eb
Revises: 
Create Date: 2018-12-28 04:00:26.388016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d9bd9e74eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('nickName', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('reg_id', sa.String(length=16), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    # ### end Alembic commands ###
