"""empty message

Revision ID: 8c98001248df
Revises: 0dabfeb70247
Create Date: 2018-12-28 06:09:59.324245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c98001248df'
down_revision = '0dabfeb70247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('avatarUr', sa.String(length=255), nullable=True))
    op.drop_column('member', 'avatarUrl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('avatarUrl', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('member', 'avatarUr')
    # ### end Alembic commands ###
