"""empty message

Revision ID: 8e57c8ddd6d7
Revises: 937496c7b64c
Create Date: 2018-12-28 05:53:37.854935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e57c8ddd6d7'
down_revision = '937496c7b64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('avatarUrl', sa.String(length=100), nullable=True))
    op.drop_column('member', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('avatar', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('member', 'avatarUrl')
    # ### end Alembic commands ###
