"""empty message

Revision ID: b80b555a167e
Revises: 258358ad087e
Create Date: 2018-12-28 04:04:03.956233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80b555a167e'
down_revision = '258358ad087e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_member_bind',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('client_type', sa.String(length=20), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('openid', sa.String(length=80), nullable=False),
    sa.Column('unionid', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('nickName', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('salt', sa.String(length=255), nullable=False),
    sa.Column('reg_id', sa.String(length=16), nullable=True),
    sa.Column('status', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    op.drop_table('auth_member_bind')
    # ### end Alembic commands ###
